// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdontoCred.Models;

namespace OdontoCred.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200826235423_Validacao1")]
    partial class Validacao1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OdontoCred.Models.CadastroCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgenciaCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CelularCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CepComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjcomercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodigoAtividadeCliente")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoBancoCliente")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoComprovacaoRendaCliente")
                        .HasColumnType("int");

                    b.Property<string>("CodigoConfirmacaoCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoConfirmacaoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplementoComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplementoResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ComprovanteEndereco")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ComprovanteEnderecoResidencial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmacaoEmailCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataConfirmacaoCelular")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConfirmacaoCodigoEmailCliente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEnvioEmailConfirmacaoCliente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimentoCliente")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("EnderecoComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FotoCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrenteDocumentoCliente")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("IdProfissao")
                        .HasColumnType("int");

                    b.Property<bool>("Negativado")
                        .HasColumnType("bit");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NomeEmpresaComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMaeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutrasRendas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RendaMensalCliente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneComercialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneResidencialCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoContaCliente")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersoDocumentoByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("VersoDocumentoCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("digitoAgenciaCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("digitoContaCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
